#' @title Process qPCR data
#' @description Performs 2^-ddCt calculations on qPCR data
#' @param qpcr_table A tibble generated by read_qpcr
#' @param metadatafile A CSV file that contains sample metadata. At least a
#'   "Sample" and"Genotype" field have to be in that file
#' @param norm Reference gene to use
#' @return A tibble containing 2^-ddCt calculations.
#' @examples
#' \dontrun{
#' calculate_qpcr(qpcr_table, norm = Gapdh)
#' }
#' @import magrittr
#' @export
calculate_qpcr <- function(qpcr_table,
                           metadatafile = "./metadata.csv",
                           norm){
  # Check if qpcr_table is the right format
  if(attr(qpcr_table,"type") != "read_qpcr"){
    stop("The input table needs to be from the read_qpcr function")
  }
  # Check if norm is set and unquote it
  if(missing(norm)){
    stop("Parameter norm is missing. You need to specify a housekeeping gene")
    }
  norm <- dplyr::enquo(norm)
  # Read the Metadata and make sure it's the right format.
  # It has to contain at least the columns Sample and Genotype
  message("Loading the Metadata.")
  metadata <- readr::read_csv(metadatafile)
  if(!all(c("Sample", "Genotype") %in% names(metadata))){
    stop("The metadata file needs to contain at least a Sample and Genotype column.")
  }
  # Do the 2^-dCT calculations
  message("Perform 2^dCT calculations.")
  qpcr_data_calculated <- qpcr_table %>%
    dplyr::select(Sample, Target, Cq_mean) %>%
    # Remove rows without a sample name (these are most likely NTCs)
    dplyr::filter(!is.na(Sample)) %>%
    tidyr::spread(key = "Target", value = "Cq_mean") %>%
    dplyr::mutate_if(is.double, dplyr::funs(dCt      = . - !!norm,
                                            `2^-dCt` = 2 ^(!!norm - .))) %>%
    dplyr::left_join(metadata, by = "Sample")
  attr(qpcr_data_calculated, "type") <- "calculate_qpcr"
  return(qpcr_data_calculated)
}
